UBE000="The guest environment variables are not present.  Execute 'guest.bash'"
UBE001="Failed to create debootstrap.packages"
UBE002="Failed to create mirror list.  Does debootstrap.packages exist?"
UBE003="No kernel specified in the top level additional.packages"
UBE004="Failed to germinate repository."
UBE005="Failed to mirror the main packages.  Check the configuration in conf/distributions."
UBE006="Failed to mirror the update packages.  Check the configuration in conf/distributions."

UBE021="Failed to create disk image.  Has KVM_IMAGE_SIZE been set in config.bash."
UBE022="Failed to label the image."
UBE023="Failed to create boot partition. Check KVM_IMAGE_BOOT parameter in config.bash."
UBE024="Failed to create root partition. Check KVM_IMAGE_ROOT parameter in config.bash."
UBE025="Failed to toggle the boot flag on partition 1."
UBE026="Failed to print partitions."
UBE027="Failed to mount the image."
UBE028="Failed to unmount the image."
UBE029="Failed to create the boot partition."
UBE030="Failed to create the root partition."
UBE031="Mounting partitions failed."
UBE032="Failed to install via the mirror and debootstrap."
UBE033="Failed to mount host directories in the chroot."

UBE040="Apt installation failed."
UBE041="Failed to configure Apt."
UBE042="Kernel installation failed."
